### ISSUE TITLE
Error with Meteor 1.3

### ISSUE THREAD

**Issue by PolGuixe** [Nemo64/meteor-bootstrap#66]
Using Meteor 1.3 beta 12

Error message: 
`Error: sourcePath not a file: bootstrap/js/transition.js
    at ImportScanner._ensureSourcePath (/tools/isobuild/import-scanner.js:208:13)
    at /tools/isobuild/import-scanner.js:101:28
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:100:11)
    at /tools/isobuild/compiler-plugin.js:709:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:689:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
    at /tools/isobuild/bundler.js:516:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
    at /tools/isobuild/bundler.js:2232:14
    at /tools/isobuild/bundler.js:2322:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.1.13-beta.12.pj5pn5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2321:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
    at /tools/runners/run-app.js:586:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:825:35)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12
`

**Comment by PolGuixe** [comment]
repo to reproduce the error: https://github.com/PolGuixe/less-bootstrap-test

**Comment by simison** [comment]
Is this same error as with 1.2? #64

**Comment by PolGuixe** [comment]
@simison not sure. However I can recommend using https://atmospherejs.com/huttonr/bootstrap3.

**Comment by emgee3** [comment]
https://github.com/nemo64/meteor-bootstrap was never updated for Meteor 1.3. https://github.com/huttonr/bootstrap3 does work in 1.3
